############################################################
# Dockerfile to build front-end angular container image
############################################################

FROM node:14

ARG WORK_DIR=/angular-hello-world
ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH

RUN mkdir ${WORK_DIR}
WORKDIR ${WORK_DIR}

COPY package.json ${WORK_DIR}
COPY package-lock.json ${WORK_DIR}

RUN npm install -g npm
RUN npm install -g @angular/cli@14.2.4
RUN npm install

COPY . ${WORK_DIR}

EXPOSE 4200

CMD ng serve --host 0.0.0.0